Account 엔티티
A-A-Ask-Answer/back-end pull request #1
Opened 2023-02-01 11:36 UTC by cousim46

Account 엔티티
- 제약조건 추가
- Account에 대한 TestCode 작성

2023-02-01 12:22 UTC, woogiekim requested changes
PR명이 조금 아쉽습니다
어떤 작업을 한것인지 명확하게 알수있는 이름이면 더 좋을거같네요

2023-02-01 12:22 UTC, woogiekim commented on src/main/java/aa/project/account/entity/Account.java
>          this.role = Role.USER;
권한이 이렇게 고정이면 createUser 와 같은 정적 팩토리 메서드가 더 좋지않을까 싶긴하네요

2023-02-01 12:22 UTC, woogiekim commented on src/test/java/aa/project/account/service/AccountServiceTest.java
>      }
아예 삭제하는게 더 낫지 않을까 싶습니다

2023-02-01 12:22 UTC, woogiekim commented on src/main/java/aa/project/account/entity/Account.java
>          this.role = Role.USER;
제약조건은 여기에 있는게 어떨까요?

그 이유에 대해서 유추해보면 좋겠네요

2023-02-01 12:35 UTC, cousim46 commented on src/test/java/aa/project/account/entity/AccountTest.java
> +
수정하겠습니다!

2023-02-01 12:37 UTC, cousim46 commented on src/main/java/aa/project/account/entity/Account.java
>          this.role = Role.USER;
제약 조건이 여기에 있어야 되는 이유는 값을 받을때 생성자를 통해 받기때문에 값 받는 부분에서 값에 대한 제약조건을 체크하는게 더 낫기 때문일까요?

2023-02-01 12:38 UTC, cousim46 commented on src/main/java/aa/project/account/entity/Account.java
> +@AllArgsConstructor
굳이 필요한거 같지는 않습니다 수정하겠습니다!

2023-02-01 12:43 UTC, woogiekim commented on src/main/java/aa/project/account/entity/Account.java
>          this.role = Role.USER;
넵 그리고 유저 객체 생성을 안전하게 하기 위함입니다

2023-02-10 20:53 UTC, woogiekim approved these changes
추가로 더 남긴 코멘트 봐주시면 좋겠습니다.
리뷰 받은 내용을 모두 반영하는게 생각보다 어렵습니다 재검토 해보는 습관을 길러보는 것도 좋을거같습니다.

고생하셨습니다! :)

2023-02-10 20:53 UTC, woogiekim commented on src/test/java/aa/project/account/entity/AccountTest.java
> +
위쪽 공백은 제거 안된거 같습니다

2023-02-10 20:53 UTC, woogiekim commented on src/test/java/aa/project/account/service/AccountServiceTest.java
>      }
삭제 하는 것 놓친거같네요

2023-02-11 15:27 UTC, merged